/**
 * Starter notes for the template gallery. Each body is markdown without the
 * `# Title` line — the notes API writes that from the (de-duplicated) title,
 * exactly as it does for a blank note. Headings are the mindmap, so every
 * template is shaped to give a readable map on its own.
 */
export type TemplateCategory = "Planning" | "Product" | "Web3" | "Learning" | "Work" | "Personal";

export type NoteTemplate = {
  id: string;
  title: string;
  category: TemplateCategory;
  description: string;
  body: string;
};

export const TEMPLATE_CATEGORIES: readonly TemplateCategory[] = [
  "Planning",
  "Product",
  "Web3",
  "Learning",
  "Work",
  "Personal",
];

const lines = (...rows: string[]) => rows.join("\n");

export const TEMPLATES: readonly NoteTemplate[] = [
  {
    id: "product-roadmap",
    title: "Product Roadmap",
    category: "Product",
    description: "Now / next / later lanes with goals and the features under each.",
    body: lines(
      "A quarter-by-quarter view of what ships and why. Link features to their specs with [[wikilinks]].",
      "",
      "## Vision",
      "One sentence on where the product is going.",
      "",
      "## Now",
      "### Onboarding revamp",
      "### Faster search",
      "### Billing fixes",
      "",
      "## Next",
      "### Team workspaces",
      "### Public API",
      "",
      "## Later",
      "### Mobile app",
      "### Integrations marketplace",
      "",
      "## Success metrics",
      "### Activation rate",
      "### Weekly active teams",
      "",
    ),
  },
  {
    id: "sprint-plan",
    title: "Sprint Plan",
    category: "Work",
    description: "Two-week sprint: goal, committed stories, risks and review.",
    body: lines(
      "Sprint dates: _start_ → _end_. Capacity: _n_ points.",
      "",
      "## Sprint goal",
      "The one outcome this sprint must deliver.",
      "",
      "## Committed",
      "### Story: sign-in with email",
      "### Story: export to PDF",
      "### Bug: slow dashboard",
      "",
      "## Stretch",
      "### Dark mode polish",
      "",
      "## Risks",
      "### Third-party API limits",
      "### Reviewer availability",
      "",
      "## Review & retro",
      "### What went well",
      "### What to change",
      "",
    ),
  },
  {
    id: "project-kickoff",
    title: "Project Kickoff",
    category: "Planning",
    description: "Scope, stakeholders, milestones and open questions for a new project.",
    body: lines(
      "Use this at the first meeting so everyone leaves with the same picture.",
      "",
      "## Why this project",
      "### Problem",
      "### Desired outcome",
      "",
      "## Scope",
      "### In scope",
      "### Out of scope",
      "",
      "## Stakeholders",
      "### Owner",
      "### Contributors",
      "### Reviewers",
      "",
      "## Milestones",
      "### M1: Discovery",
      "### M2: Build",
      "### M3: Launch",
      "",
      "## Open questions",
      "",
    ),
  },
  {
    id: "grant-proposal",
    title: "Grant Proposal",
    category: "Web3",
    description: "Problem, deliverables, budget and evidence, ready for a grant program.",
    body: lines(
      "Structure a grant or ecosystem-fund application around verifiable deliverables.",
      "",
      "## Problem",
      "### Who has it",
      "### Why now",
      "",
      "## Solution",
      "### How it works",
      "### Why on Stellar",
      "",
      "## Deliverables",
      "### D1: Smart contract",
      "### D2: SDK",
      "### D3: Documentation",
      "",
      "## Budget",
      "### Development",
      "### QA and testing",
      "",
      "## Evidence of completion",
      "### Transaction links",
      "### Repository and CI",
      "",
      "## Timeline",
      "### Week 1",
      "### Week 2",
      "### Week 3",
      "### Week 4",
      "",
    ),
  },
  {
    id: "smart-contract-launch",
    title: "Smart Contract Launch",
    category: "Web3",
    description: "From spec to testnet: design, tests, deployment and verification.",
    body: lines(
      "A launch checklist for a Soroban contract. Anchor each milestone once it ships.",
      "",
      "## Specification",
      "### Storage layout",
      "### Authorization rules",
      "### Events",
      "",
      "## Implementation",
      "### Core functions",
      "### Error handling",
      "",
      "## Testing",
      "### Unit tests",
      "### Negative auth cases",
      "### Property tests",
      "",
      "## Testnet deployment",
      "### Deploy script",
      "### TypeScript bindings",
      "### Explorer verification",
      "",
      "## Security review",
      "### Threat model",
      "### Known limitations",
      "",
    ),
  },
  {
    id: "hackathon-project",
    title: "Hackathon Project",
    category: "Web3",
    description: "Idea to demo in a weekend: pitch, MVP features, team split and demo script.",
    body: lines(
      "Keep it small enough to demo. Cut anything that is not on the demo path.",
      "",
      "## Pitch",
      "### One-line idea",
      "### Target user",
      "",
      "## MVP",
      "### Must have",
      "### Nice to have",
      "",
      "## Tech stack",
      "### Frontend",
      "### Contract",
      "### Data",
      "",
      "## Team",
      "### Builder",
      "### Designer",
      "### Presenter",
      "",
      "## Demo script",
      "### Setup",
      "### Wow moment",
      "### Close",
      "",
    ),
  },
  {
    id: "business-plan",
    title: "Lean Business Plan",
    category: "Planning",
    description: "Lean-canvas style plan: customers, value, channels, revenue and costs.",
    body: lines(
      "A one-page plan you can test, not a document you file away.",
      "",
      "## Customer segments",
      "### Early adopters",
      "",
      "## Problem",
      "### Top three problems",
      "### Existing alternatives",
      "",
      "## Value proposition",
      "",
      "## Channels",
      "### Organic",
      "### Partnerships",
      "",
      "## Revenue",
      "### Pricing",
      "### Lifetime value",
      "",
      "## Costs",
      "### Fixed",
      "### Variable",
      "",
      "## Key metrics",
      "",
    ),
  },
  {
    id: "course-notes",
    title: "Course Notes",
    category: "Learning",
    description: "Modules, key concepts and review questions for a class or online course.",
    body: lines(
      "One heading per module. Link concepts that show up in several modules with [[wikilinks]].",
      "",
      "## Module 1: Foundations",
      "### Key concepts",
      "### Examples",
      "",
      "## Module 2: Core techniques",
      "### Key concepts",
      "### Exercises",
      "",
      "## Module 3: Applications",
      "### Case studies",
      "",
      "## Review",
      "### Questions I still have",
      "### Exam checklist",
      "",
    ),
  },
  {
    id: "research-paper",
    title: "Research Paper",
    category: "Learning",
    description: "Paper outline from question to conclusion, with literature and methods.",
    body: lines(
      "Draft the argument as headings first; the mindmap shows whether it holds together.",
      "",
      "## Research question",
      "",
      "## Literature review",
      "### Prior work",
      "### Gap",
      "",
      "## Method",
      "### Data",
      "### Analysis",
      "",
      "## Results",
      "### Finding 1",
      "### Finding 2",
      "",
      "## Discussion",
      "### Limitations",
      "### Future work",
      "",
      "## Conclusion",
      "",
    ),
  },
  {
    id: "meeting-notes",
    title: "Meeting Notes",
    category: "Work",
    description: "Agenda, decisions and action items so nothing gets lost after the call.",
    body: lines(
      "Date: _today_. Attendees: _names_.",
      "",
      "## Agenda",
      "### Topic 1",
      "### Topic 2",
      "",
      "## Decisions",
      "",
      "## Action items",
      "### Owner: task, due date",
      "",
      "## Follow-ups",
      "",
    ),
  },
  {
    id: "incident-postmortem",
    title: "Incident Postmortem",
    category: "Work",
    description: "Blameless review: timeline, root cause, impact and fixes.",
    body: lines(
      "Blameless: focus on systems and signals, not people.",
      "",
      "## Summary",
      "",
      "## Impact",
      "### Users affected",
      "### Duration",
      "",
      "## Timeline",
      "### Detection",
      "### Mitigation",
      "### Resolution",
      "",
      "## Root cause",
      "### Contributing factors",
      "",
      "## Action items",
      "### Prevent",
      "### Detect faster",
      "### Respond better",
      "",
    ),
  },
  {
    id: "marketing-campaign",
    title: "Marketing Campaign",
    category: "Product",
    description: "Audience, message, channels, content calendar and results.",
    body: lines(
      "Plan the launch and measure what actually moved the numbers.",
      "",
      "## Goal",
      "",
      "## Audience",
      "### Primary",
      "### Secondary",
      "",
      "## Message",
      "### Headline",
      "### Proof points",
      "",
      "## Channels",
      "### Social",
      "### Email",
      "### Community",
      "",
      "## Content calendar",
      "### Week 1: Teaser",
      "### Week 2: Launch",
      "### Week 3: Follow-up",
      "",
      "## Results",
      "",
    ),
  },
  {
    id: "event-plan",
    title: "Event Plan",
    category: "Planning",
    description: "Meetup or workshop: venue, agenda, speakers, promotion and logistics.",
    body: lines(
      "Everything for a meetup or workshop in one map.",
      "",
      "## Overview",
      "### Date and venue",
      "### Expected attendees",
      "",
      "## Agenda",
      "### Opening",
      "### Talks",
      "### Workshop",
      "### Networking",
      "",
      "## Speakers",
      "",
      "## Promotion",
      "### Registration page",
      "### Social posts",
      "",
      "## Logistics",
      "### Food",
      "### Equipment",
      "### Volunteers",
      "",
    ),
  },
  {
    id: "personal-goals",
    title: "Personal Goals",
    category: "Personal",
    description: "Yearly goals by life area, broken into quarterly milestones and habits.",
    body: lines(
      "Pick a few areas. Each goal gets milestones you can actually check off.",
      "",
      "## Health",
      "### Exercise three times a week",
      "### Sleep before midnight",
      "",
      "## Career",
      "### Ship a side project",
      "### Learn a new language",
      "",
      "## Learning",
      "### Read 12 books",
      "",
      "## Finance",
      "### Emergency fund",
      "",
      "## Quarterly review",
      "### Q1",
      "### Q2",
      "### Q3",
      "### Q4",
      "",
    ),
  },
];

/** The body a template contributes, with the title line the API would write. */
export function templateMarkdown(template: NoteTemplate): string {
  return `# ${template.title}\n\n${template.body}`;
}
